@Library('jenkins-pipeline-libs')
import lulu.jenkins.utils.*
import lulu.jenkins.ci.*

node ("ci") {

    def pipeline = new K8sServicePipeline(this)
    pipeline.projectName = "dummy-app-service"
    pipeline.dockerImageName = "dummy-app"

    pipeline.setBranchProperties()
    pipeline.run()

}
